# generated by datamodel-codegen:
#   filename:  openresponses.openapi.no_discriminator.json
#   timestamp: 2026-03-06T07:13:09+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint, constr, field_validator


class ItemReferenceParam(BaseModel):
    type: Literal["item_reference"] | None = None
    id: str = Field(..., description="The ID of the item to reference.")


class ReasoningSummaryContentParam(BaseModel):
    type: Literal["summary_text"] = Field(
        ..., description="The content type. Always `summary_text`."
    )
    text: constr(max_length=10485760) = Field(..., description="The reasoning summary text.")


class ReasoningItemParam(BaseModel):
    id: str | None = None
    type: Literal["reasoning"] = Field(..., description="The item type. Always `reasoning`.")
    summary: list[ReasoningSummaryContentParam] = Field(
        ..., description="Reasoning summary content associated with this item."
    )
    content: None = None
    encrypted_content: str | None = None


class InputTextContentParam(BaseModel):
    type: Literal["input_text"] = Field(
        ..., description="The type of the input item. Always `input_text`."
    )
    text: constr(max_length=10485760) = Field(..., description="The text input to the model.")


class DetailEnum(Enum):
    low = "low"
    high = "high"
    auto = "auto"


class InputFileContentParam(BaseModel):
    type: Literal["input_file"] = Field(
        ..., description="The type of the input item. Always `input_file`."
    )
    filename: str | None = None
    file_data: constr(max_length=33554432) | None = None
    file_url: str | None = None


class SystemMessageItemParam(BaseModel):
    id: str | None = None
    type: Literal["message"] = Field(..., description="The item type. Always `message`.")
    role: Literal["system"] = Field(..., description="The message role. Always `system`.")
    content: list[InputTextContentParam] | constr(
        max_length=10485760
    ) = Field(..., description="The message content, as an array of content parts.")
    status: str | None = None


class DeveloperMessageItemParam(BaseModel):
    id: str | None = None
    type: Literal["message"] = Field(..., description="The item type. Always `message`.")
    role: Literal["developer"] = Field(..., description="The message role. Always `developer`.")
    content: list[InputTextContentParam] | constr(
        max_length=10485760
    ) = Field(..., description="The message content, as an array of content parts.")
    status: str | None = None


class UrlCitationParam(BaseModel):
    type: Literal["url_citation"] = Field(
        ..., description="The citation type. Always `url_citation`."
    )
    start_index: conint(ge=0) = Field(
        ...,
        description="The index of the first character of the citation in the message.",
    )
    end_index: conint(ge=0) = Field(
        ...,
        description="The index of the last character of the citation in the message.",
    )
    url: str = Field(..., description="The URL of the cited resource.")
    title: str = Field(..., description="The title of the cited resource.")


class OutputTextContentParam(BaseModel):
    type: Literal["output_text"] = Field(..., description="The content type. Always `output_text`.")
    text: constr(max_length=10485760) = Field(..., description="The text content.")
    annotations: list[UrlCitationParam] | None = Field(
        None, description="Citations associated with the text content."
    )


class RefusalContentParam(BaseModel):
    type: Literal["refusal"] = Field(..., description="The content type. Always `refusal`.")
    refusal: constr(max_length=10485760) = Field(..., description="The refusal text.")


class AssistantMessageItemParam(BaseModel):
    id: str | None = None
    type: Literal["message"] = Field(..., description="The item type. Always `message`.")
    role: Literal["assistant"] = Field(
        ..., description="The role of the message author. Always `assistant`."
    )
    content: list[OutputTextContentParam | RefusalContentParam] | constr(
        max_length=10485760
    ) = Field(..., description="The message content, as an array of content parts.")
    status: str | None = None


class FunctionCallItemStatus(Enum):
    in_progress = "in_progress"
    completed = "completed"
    incomplete = "incomplete"


class IncludeEnum(Enum):
    reasoning_encrypted_content = "reasoning.encrypted_content"
    message_output_text_logprobs = "message.output_text.logprobs"


class EmptyModelParam(BaseModel):
    pass


class FunctionToolParam(BaseModel):
    name: constr(pattern=r"^[a-zA-Z0-9_-]+$", min_length=1, max_length=64)
    description: str | None = None
    parameters: dict[str, Any] | None = None
    strict: bool | None = None
    type: Literal["function"]


class GenericToolParam(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: constr(min_length=1, max_length=128)
    description: str | None = None

    @field_validator("type")
    @classmethod
    def validate_type(cls, value: str) -> str:
        if value == "function":
            raise ValueError("generic tool type must not be 'function'")
        return value


class ResponsesToolParam(RootModel[FunctionToolParam | GenericToolParam]):
    root: FunctionToolParam | GenericToolParam


class SpecificFunctionParam(BaseModel):
    type: Literal["function"] = Field(..., description="The tool to call. Always `function`.")
    name: str = Field(..., description="The name of the function tool to call.")


class SpecificGenericToolParam(BaseModel):
    type: constr(min_length=1, max_length=128) = Field(
        ..., description="The non-function tool type to call."
    )

    @field_validator("type")
    @classmethod
    def validate_type(cls, value: str) -> str:
        if value == "function":
            raise ValueError("generic tool choice type must not be 'function'")
        return value


class SpecificToolChoiceParam(RootModel[SpecificFunctionParam | SpecificGenericToolParam]):
    root: SpecificFunctionParam | SpecificGenericToolParam


class ToolChoiceValueEnum(Enum):
    none = "none"
    auto = "auto"
    required = "required"


class AllowedToolsParam(BaseModel):
    type: Literal["allowed_tools"] = Field(
        ..., description="The tool choice type. Always `allowed_tools`."
    )
    tools: list[SpecificToolChoiceParam] = Field(
        ...,
        description="The list of tools that are permitted for this request.",
        max_length=128,
        min_length=1,
    )
    mode: ToolChoiceValueEnum | None = None


class ToolChoiceParam(RootModel[SpecificToolChoiceParam | ToolChoiceValueEnum | AllowedToolsParam]):
    root: SpecificToolChoiceParam | ToolChoiceValueEnum | AllowedToolsParam = Field(
        ..., description="Controls which tool the model should use, if any."
    )


class MetadataParam(RootModel[dict[str, constr(max_length=512)]]):
    root: dict[str, constr(max_length=512)]


class VerbosityEnum(Enum):
    low = "low"
    medium = "medium"
    high = "high"


class StreamOptionsParam(BaseModel):
    include_obfuscation: bool | None = Field(
        None,
        description="Whether to obfuscate sensitive information in streamed output. Defaults to `true`.",
    )


class ReasoningEffortEnum(Enum):
    none = "none"
    low = "low"
    medium = "medium"
    high = "high"
    xhigh = "xhigh"


class ReasoningSummaryEnum(Enum):
    concise = "concise"
    detailed = "detailed"
    auto = "auto"


class ReasoningParam(BaseModel):
    effort: ReasoningEffortEnum | None = None
    summary: ReasoningSummaryEnum | None = None


class TruncationEnum(Enum):
    auto = "auto"
    disabled = "disabled"


class ServiceTierEnum(Enum):
    auto = "auto"
    default = "default"
    flex = "flex"
    priority = "priority"


class ToolChoice1(BaseModel):
    pass


class ToolChoice2(ToolChoice1):
    pass


class ToolChoice3(Enum):
    none = "none"
    auto = "auto"
    required = "required"


class ToolChoice4(AllowedToolsParam, ToolChoice1):
    pass


class ToolChoice(RootModel[ToolChoice2 | ToolChoice3 | ToolChoice4]):
    root: ToolChoice2 | ToolChoice3 | ToolChoice4


class IncompleteDetails(BaseModel):
    reason: str = Field(..., description="The reason the response could not be completed.")


class MessageRole(Enum):
    user = "user"
    assistant = "assistant"
    system = "system"
    developer = "developer"


class InputTextContent(BaseModel):
    type: Literal["input_text"] = Field(
        ..., description="The type of the input item. Always `input_text`."
    )
    text: str = Field(..., description="The text input to the model.")


class UrlCitationBody(BaseModel):
    type: Literal["url_citation"] = Field(
        ..., description="The type of the URL citation. Always `url_citation`."
    )
    url: str = Field(..., description="The URL of the web resource.")
    start_index: int = Field(
        ...,
        description="The index of the first character of the URL citation in the message.",
    )
    end_index: int = Field(
        ...,
        description="The index of the last character of the URL citation in the message.",
    )
    title: str = Field(..., description="The title of the web resource.")


class Annotation(RootModel[UrlCitationBody]):
    root: UrlCitationBody = Field(
        ..., description="An annotation that applies to a span of output text."
    )


class TopLogProb(BaseModel):
    token: str
    logprob: float
    bytes: list[int]


class LogProb(BaseModel):
    token: str
    logprob: float
    bytes: list[int]
    top_logprobs: list[TopLogProb]


class OutputTextContent(BaseModel):
    type: Literal["output_text"] = Field(
        ..., description="The type of the output text. Always `output_text`."
    )
    text: str = Field(..., description="The text output from the model.")
    annotations: list[Annotation] = Field(..., description="The annotations of the text output.")
    logprobs: list[LogProb] | None = None


class TextContent(BaseModel):
    type: Literal["text"]
    text: str


class SummaryTextContent(BaseModel):
    type: Literal["summary_text"] = Field(
        ..., description="The type of the object. Always `summary_text`."
    )
    text: str = Field(..., description="A summary of the reasoning output from the model so far.")


class ReasoningTextContent(BaseModel):
    type: Literal["reasoning_text"] = Field(
        ..., description="The type of the reasoning text. Always `reasoning_text`."
    )
    text: str = Field(..., description="The reasoning text from the model.")


class RefusalContent(BaseModel):
    type: Literal["refusal"] = Field(..., description="The type of the refusal. Always `refusal`.")
    refusal: str = Field(..., description="The refusal explanation from the model.")


class ImageDetail(Enum):
    low = "low"
    high = "high"
    auto = "auto"


class InputImageContent(BaseModel):
    type: Literal["input_image"] = Field(
        ..., description="The type of the input item. Always `input_image`."
    )
    image_url: str | None
    detail: ImageDetail


class InputFileContent(BaseModel):
    type: Literal["input_file"] = Field(
        ..., description="The type of the input item. Always `input_file`."
    )
    filename: str | None = Field(None, description="The name of the file to be sent to the model.")
    file_url: str | None = Field(None, description="The URL of the file to be sent to the model.")


class MessageStatus(Enum):
    in_progress = "in_progress"
    completed = "completed"
    incomplete = "incomplete"


class FunctionCallStatus(Enum):
    in_progress = "in_progress"
    completed = "completed"
    incomplete = "incomplete"


class FunctionCall(BaseModel):
    type: Literal["function_call"] = Field(
        ..., description="The type of the item. Always `function_call`."
    )
    id: str = Field(..., description="The unique ID of the function call item.")
    call_id: str = Field(
        ..., description="The unique ID of the function tool call that was generated."
    )
    name: str = Field(..., description="The name of the function that was called.")
    arguments: str = Field(..., description="The arguments JSON string that was generated.")
    status: FunctionCallStatus


class FunctionCallOutputStatusEnum(Enum):
    in_progress = "in_progress"
    completed = "completed"
    incomplete = "incomplete"


class FunctionCallOutput(BaseModel):
    type: Literal["function_call_output"] = Field(
        ...,
        description="The type of the function tool call output. Always `function_call_output`.",
    )
    id: str = Field(
        ...,
        description="The unique ID of the function tool call output. Populated when this item is returned via API.",
    )
    call_id: str = Field(
        ...,
        description="The unique ID of the function tool call generated by the model.",
    )
    output: str | list[InputTextContent | InputImageContent | InputFileContent]
    status: FunctionCallOutputStatusEnum


class ReasoningBody(BaseModel):
    type: Literal["reasoning"] = Field(..., description="The type of the item. Always `reasoning`.")
    id: str = Field(..., description="The unique ID of the reasoning item.")
    content: (
        list[
            InputTextContent
            | OutputTextContent
            | TextContent
            | SummaryTextContent
            | ReasoningTextContent
            | RefusalContent
            | InputImageContent
            | InputFileContent
        ]
        | None
    ) = Field(None, description="The reasoning content that was generated.")
    summary: list[
        InputTextContent
        | OutputTextContent
        | TextContent
        | SummaryTextContent
        | ReasoningTextContent
        | RefusalContent
        | InputImageContent
        | InputFileContent
    ] = Field(..., description="The reasoning summary content that was generated.")
    encrypted_content: str | None = Field(
        None, description="The encrypted reasoning content that was generated."
    )


class Error(BaseModel):
    code: str = Field(..., description="A machine-readable error code that was returned.")
    message: str = Field(
        ..., description="A human-readable description of the error that was returned."
    )


class FunctionTool(BaseModel):
    type: Literal["function"] = Field(
        ..., description="The type of the function tool. Always `function`."
    )
    name: str = Field(..., description="The name of the function to call.")
    description: str | None
    parameters: dict[str, Any] | None
    strict: bool | None


class GenericTool(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: constr(min_length=1, max_length=128) = Field(
        ..., description="The non-function tool type."
    )
    description: str | None = None

    @field_validator("type")
    @classmethod
    def validate_type(cls, value: str) -> str:
        if value == "function":
            raise ValueError("generic tool type must not be 'function'")
        return value


class Tool(RootModel[FunctionTool | GenericTool]):
    root: FunctionTool | GenericTool = Field(
        ..., description="A tool that can be used to generate a response."
    )


class FunctionToolChoice(BaseModel):
    type: Literal["function"]
    name: str | None = None


class GenericToolChoice(BaseModel):
    type: constr(min_length=1, max_length=128)

    @field_validator("type")
    @classmethod
    def validate_type(cls, value: str) -> str:
        if value == "function":
            raise ValueError("generic tool choice type must not be 'function'")
        return value


class AllowedToolChoice(BaseModel):
    type: Literal["allowed_tools"]
    tools: list[FunctionToolChoice | GenericToolChoice]
    mode: ToolChoiceValueEnum


class TextResponseFormat(BaseModel):
    type: Literal["text"]


class JsonObjectResponseFormat(BaseModel):
    type: Literal["json_object"]


class JsonSchemaResponseFormat(BaseModel):
    type: Literal["json_schema"]
    name: str
    description: str | None
    schema_: None = Field(..., alias="schema")
    strict: bool


class TextField(BaseModel):
    format: TextResponseFormat | JsonObjectResponseFormat | JsonSchemaResponseFormat
    verbosity: VerbosityEnum | None = None


class Reasoning(BaseModel):
    effort: ReasoningEffortEnum | None
    summary: ReasoningSummaryEnum | None


class InputTokensDetails(BaseModel):
    cached_tokens: int = Field(
        ..., description="The number of input tokens that were served from cache."
    )


class OutputTokensDetails(BaseModel):
    reasoning_tokens: int = Field(
        ...,
        description="The number of output tokens that were attributed to reasoning.",
    )


class Usage(BaseModel):
    input_tokens: int = Field(
        ...,
        description="The number of input tokens that were used to generate the response.",
    )
    output_tokens: int = Field(
        ..., description="The number of output tokens that were generated by the model."
    )
    total_tokens: int = Field(..., description="The total number of tokens that were used.")
    input_tokens_details: InputTokensDetails
    output_tokens_details: OutputTokensDetails


class Item1(BaseModel):
    pass


class Item3(FunctionCall, Item1):
    pass


class Item4(FunctionCallOutput, Item1):
    pass


class Item5(ReasoningBody, Item1):
    pass


class Item61(BaseModel):
    pass


class Item63(FunctionCall, Item61):
    pass


class Item64(FunctionCallOutput, Item61):
    pass


class Item65(ReasoningBody, Item61):
    pass


class ResponseReasoningSummaryPartAddedStreamingEvent(BaseModel):
    type: Literal["response.reasoning_summary_part.added"] = Field(
        ...,
        description="The type of the event, always `response.reasoning_summary_part.added`.",
    )
    sequence_number: int = Field(
        ..., description="The sequence number of the event that was emitted."
    )
    item_id: str = Field(..., description="The ID of the item that was updated.")
    output_index: int = Field(..., description="The index of the output item that was updated.")
    summary_index: int = Field(..., description="The index of the summary part that was added.")
    part: (
        InputTextContent
        | OutputTextContent
        | TextContent
        | SummaryTextContent
        | ReasoningTextContent
        | RefusalContent
        | InputImageContent
        | InputFileContent
    ) = Field(..., description="A content part that makes up an input or output item.")


class ResponseReasoningSummaryPartDoneStreamingEvent(BaseModel):
    type: Literal["response.reasoning_summary_part.done"] = Field(
        ...,
        description="The type of the event, always `response.reasoning_summary_part.done`.",
    )
    sequence_number: int = Field(
        ..., description="The sequence number of the event that was emitted."
    )
    item_id: str = Field(..., description="The ID of the item that was updated.")
    output_index: int = Field(..., description="The index of the output item that was updated.")
    summary_index: int = Field(..., description="The index of the summary part that was completed.")
    part: (
        InputTextContent
        | OutputTextContent
        | TextContent
        | SummaryTextContent
        | ReasoningTextContent
        | RefusalContent
        | InputImageContent
        | InputFileContent
    ) = Field(..., description="A content part that makes up an input or output item.")


class ResponseContentPartAddedStreamingEvent(BaseModel):
    type: Literal["response.content_part.added"] = Field(
        ..., description="The type of the event, always `response.content_part.added`."
    )
    sequence_number: int = Field(
        ..., description="The sequence number of the event that was emitted."
    )
    item_id: str = Field(..., description="The ID of the item that was updated.")
    output_index: int = Field(..., description="The index of the output item that was updated.")
    content_index: int = Field(..., description="The index of the content part that was added.")
    part: (
        InputTextContent
        | OutputTextContent
        | TextContent
        | SummaryTextContent
        | ReasoningTextContent
        | RefusalContent
        | InputImageContent
        | InputFileContent
    ) = Field(..., description="A content part that makes up an input or output item.")


class ResponseContentPartDoneStreamingEvent(BaseModel):
    type: Literal["response.content_part.done"] = Field(
        ..., description="The type of the event, always `response.content_part.done`."
    )
    sequence_number: int = Field(
        ..., description="The sequence number of the event that was emitted."
    )
    item_id: str = Field(..., description="The ID of the item that was updated.")
    output_index: int = Field(..., description="The index of the output item that was updated.")
    content_index: int = Field(..., description="The index of the content part that was completed.")
    part: (
        InputTextContent
        | OutputTextContent
        | TextContent
        | SummaryTextContent
        | ReasoningTextContent
        | RefusalContent
        | InputImageContent
        | InputFileContent
    ) = Field(..., description="A content part that makes up an input or output item.")


class ResponseOutputTextDeltaStreamingEvent(BaseModel):
    type: Literal["response.output_text.delta"] = Field(
        ..., description="The type of the event, always `response.output_text.delta`."
    )
    sequence_number: int = Field(
        ..., description="The sequence number of the event that was emitted."
    )
    item_id: str = Field(..., description="The ID of the item that was updated.")
    output_index: int = Field(..., description="The index of the output item that was updated.")
    content_index: int = Field(..., description="The index of the content part that was updated.")
    delta: str = Field(..., description="The text delta that was appended.")
    logprobs: list[LogProb] | None = Field(
        None,
        description="The token log probabilities that were emitted with the delta, if any.",
    )
    obfuscation: str | None = Field(
        None,
        description="An obfuscation string that was added to pad the event payload.",
    )


class ResponseOutputTextDoneStreamingEvent(BaseModel):
    type: Literal["response.output_text.done"] = Field(
        ..., description="The type of the event, always `response.output_text.done`."
    )
    sequence_number: int = Field(
        ..., description="The sequence number of the event that was emitted."
    )
    item_id: str = Field(..., description="The ID of the item that was updated.")
    output_index: int = Field(..., description="The index of the output item that was updated.")
    content_index: int = Field(..., description="The index of the content part that was completed.")
    text: str = Field(..., description="The final text that was emitted.")
    logprobs: list[LogProb] | None = Field(
        None,
        description="The token log probabilities that were emitted with the final text, if any.",
    )


class ResponseRefusalDeltaStreamingEvent(BaseModel):
    type: Literal["response.refusal.delta"] = Field(
        ..., description="The type of the event, always `response.refusal.delta`."
    )
    sequence_number: int = Field(
        ..., description="The sequence number of the event that was emitted."
    )
    item_id: str = Field(..., description="The ID of the item that was updated.")
    output_index: int = Field(..., description="The index of the output item that was updated.")
    content_index: int = Field(
        ..., description="The index of the refusal content that was updated."
    )
    delta: str = Field(..., description="The refusal text delta that was appended.")


class ResponseRefusalDoneStreamingEvent(BaseModel):
    type: Literal["response.refusal.done"] = Field(
        ..., description="The type of the event, always `response.refusal.done`."
    )
    sequence_number: int = Field(
        ..., description="The sequence number of the event that was emitted."
    )
    item_id: str = Field(..., description="The ID of the item that was updated.")
    output_index: int = Field(..., description="The index of the output item that was updated.")
    content_index: int = Field(
        ..., description="The index of the refusal content that was completed."
    )
    refusal: str = Field(..., description="The final refusal text that was emitted.")


class ResponseReasoningDeltaStreamingEvent(BaseModel):
    type: Literal["response.reasoning.delta"] = Field(
        ..., description="The type of the event, always `response.reasoning.delta`."
    )
    sequence_number: int = Field(
        ..., description="The sequence number of the event that was emitted."
    )
    item_id: str = Field(..., description="The ID of the item that was updated.")
    output_index: int = Field(..., description="The index of the output item that was updated.")
    content_index: int = Field(
        ..., description="The index of the reasoning content that was updated."
    )
    delta: str = Field(..., description="The reasoning text delta that was appended.")
    obfuscation: str | None = Field(
        None,
        description="An obfuscation string that was added to pad the event payload.",
    )


class ResponseReasoningDoneStreamingEvent(BaseModel):
    type: Literal["response.reasoning.done"] = Field(
        ..., description="The type of the event, always `response.reasoning.done`."
    )
    sequence_number: int = Field(
        ..., description="The sequence number of the event that was emitted."
    )
    item_id: str = Field(..., description="The ID of the item that was updated.")
    output_index: int = Field(..., description="The index of the output item that was updated.")
    content_index: int = Field(
        ..., description="The index of the reasoning content that was completed."
    )
    text: str = Field(..., description="The final reasoning text that was emitted.")


class ResponseReasoningSummaryDeltaStreamingEvent(BaseModel):
    type: Literal["response.reasoning_summary_text.delta"] = Field(
        ...,
        description="The type of the event, always `response.reasoning_summary.delta`.",
    )
    sequence_number: int = Field(
        ..., description="The sequence number of the event that was emitted."
    )
    item_id: str = Field(..., description="The ID of the item that was updated.")
    output_index: int = Field(..., description="The index of the output item that was updated.")
    summary_index: int = Field(
        ..., description="The index of the summary content that was updated."
    )
    delta: str = Field(..., description="The summary text delta that was appended.")
    obfuscation: str | None = Field(
        None,
        description="An obfuscation string that was added to pad the event payload.",
    )


class ResponseReasoningSummaryDoneStreamingEvent(BaseModel):
    type: Literal["response.reasoning_summary_text.done"] = Field(
        ...,
        description="The type of the event, always `response.reasoning_summary.done`.",
    )
    sequence_number: int = Field(
        ..., description="The sequence number of the event that was emitted."
    )
    item_id: str = Field(..., description="The ID of the item that was updated.")
    output_index: int = Field(..., description="The index of the output item that was updated.")
    summary_index: int = Field(
        ..., description="The index of the summary content that was completed."
    )
    text: str = Field(..., description="The final summary text that was emitted.")


class Annotation11(BaseModel):
    pass


class Annotation12(UrlCitationBody, Annotation11):
    pass


class Annotation1(RootModel[Annotation12]):
    root: Annotation12


class ResponseOutputTextAnnotationAddedStreamingEvent(BaseModel):
    type: Literal["response.output_text.annotation.added"] = Field(
        ...,
        description="The type of the event, always `response.output_text.annotation.added`.",
    )
    sequence_number: int = Field(
        ..., description="The sequence number of the event that was emitted."
    )
    item_id: str = Field(..., description="The ID of the item that was updated.")
    output_index: int = Field(..., description="The index of the output item that was updated.")
    content_index: int = Field(
        ..., description="The index of the output text content that was updated."
    )
    annotation_index: int = Field(..., description="The index of the annotation that was added.")
    annotation: Annotation1 | None


class ResponseFunctionCallArgumentsDeltaStreamingEvent(BaseModel):
    type: Literal["response.function_call_arguments.delta"] = Field(
        ...,
        description="The type of the event, always `response.function_call_arguments.delta`.",
    )
    sequence_number: int = Field(
        ..., description="The sequence number of the event that was emitted."
    )
    item_id: str = Field(..., description="The ID of the tool call item that was updated.")
    output_index: int = Field(..., description="The index of the output item that was updated.")
    delta: str = Field(..., description="The arguments delta that was appended.")
    obfuscation: str | None = Field(
        None,
        description="An obfuscation string that was added to pad the event payload.",
    )


class ResponseFunctionCallArgumentsDoneStreamingEvent(BaseModel):
    type: Literal["response.function_call_arguments.done"] = Field(
        ...,
        description="The type of the event, always `response.function_call_arguments.done`.",
    )
    sequence_number: int = Field(
        ..., description="The sequence number of the event that was emitted."
    )
    item_id: str = Field(..., description="The ID of the tool call item that was updated.")
    output_index: int = Field(..., description="The index of the output item that was updated.")
    arguments: str = Field(..., description="The final arguments string that was emitted.")


class ErrorPayload(BaseModel):
    type: str = Field(..., description="The error type that was emitted.")
    code: str | None
    message: str = Field(..., description="The human-readable error message that was emitted.")
    param: str | None
    headers: dict[str, str] | None = Field(
        None,
        description="The response headers that were emitted with the error, if any.",
    )


class ErrorStreamingEvent(BaseModel):
    type: Literal["error"] = Field(..., description="The type of the event, always `error`.")
    sequence_number: int = Field(
        ..., description="The sequence number of the event that was emitted."
    )
    error: ErrorPayload


class InputVideoContent(BaseModel):
    type: Literal["input_video"] = Field(
        ..., description="The type of the input content. Always `input_video`."
    )
    video_url: str = Field(..., description="A base64 or remote url that resolves to a video file.")


class JsonSchemaResponseFormatParam(BaseModel):
    type: Literal["json_schema"] | None = Field(
        None,
        description="The type of response format being defined. Always `json_schema`.",
    )
    description: str | None = Field(
        None,
        description="A description of what the response format is for, used by the model to\ndetermine how to respond in the format.\n",
    )
    name: str | None = Field(
        None,
        description="The name of the response format. Must be a-z, A-Z, 0-9, or contain\nunderscores and dashes, with a maximum length of 64.\n",
    )
    schema_: dict[str, Any] | None = Field(
        None,
        alias="schema",
        description="The schema for the response format, described as a JSON Schema object.\n",
        title="JSON schema",
    )
    strict: bool | None = None


class TextFormatParam(RootModel[TextResponseFormat | JsonSchemaResponseFormatParam]):
    root: TextResponseFormat | JsonSchemaResponseFormatParam


class InputImageContentParamAutoParam(BaseModel):
    type: Literal["input_image"] = Field(
        ..., description="The type of the input item. Always `input_image`."
    )
    image_url: constr(max_length=20971520) | None = None
    detail: ImageDetail | None = None


class UserMessageItemParam(BaseModel):
    id: str | None = None
    type: Literal["message"] = Field(..., description="The item type. Always `message`.")
    role: Literal["user"] = Field(..., description="The message role. Always `user`.")
    content: list[
        InputTextContentParam | InputImageContentParamAutoParam | InputFileContentParam
    ] | constr(
        max_length=10485760
    ) = Field(..., description="The message content, as an array of content parts.")
    status: str | None = None


class FunctionCallItemParam(BaseModel):
    id: str | None = None
    call_id: constr(min_length=1, max_length=64) = Field(
        ...,
        description="The unique ID of the function tool call generated by the model.",
    )
    type: Literal["function_call"] = Field(
        ..., description="The item type. Always `function_call`."
    )
    name: constr(pattern=r"^[a-zA-Z0-9_-]+$", min_length=1, max_length=64) = Field(
        ..., description="The name of the function to call."
    )
    arguments: str = Field(..., description="The function arguments as a JSON string.")
    status: FunctionCallStatus | None = None


class FunctionCallOutputItemParam(BaseModel):
    id: str | None = None
    call_id: constr(min_length=1, max_length=64) = Field(
        ...,
        description="The unique ID of the function tool call generated by the model.",
    )
    type: Literal["function_call_output"] = Field(
        ...,
        description="The type of the function tool call output. Always `function_call_output`.",
    )
    output: (
        constr(max_length=10485760)
        | list[
            InputTextContentParam
            | InputImageContentParamAutoParam
            | InputFileContentParam
            | InputVideoContent
        ]
    ) = Field(..., description="Text, image, or file output of the function tool call.")
    status: FunctionCallStatus | None = None


class ItemParam(
    RootModel[
        ItemReferenceParam
        | ReasoningItemParam
        | UserMessageItemParam
        | SystemMessageItemParam
        | DeveloperMessageItemParam
        | AssistantMessageItemParam
        | FunctionCallItemParam
        | FunctionCallOutputItemParam
    ]
):
    root: (
        ItemReferenceParam
        | ReasoningItemParam
        | UserMessageItemParam
        | SystemMessageItemParam
        | DeveloperMessageItemParam
        | AssistantMessageItemParam
        | FunctionCallItemParam
        | FunctionCallOutputItemParam
    )


class TextParam(BaseModel):
    format: TextFormatParam | None = Field(
        None, description="The format configuration for text output."
    )
    verbosity: VerbosityEnum | None = None


class CreateResponseBody(BaseModel):
    model: str | None = None
    input: constr(max_length=10485760) | list[ItemParam] | None = None
    previous_response_id: str | None = None
    include: list[IncludeEnum] | None = None
    tools: list[ResponsesToolParam] | None = None
    tool_choice: ToolChoice | None = None
    metadata: MetadataParam | None = None
    text: TextParam | None = None
    temperature: float | None = None
    top_p: float | None = None
    presence_penalty: float | None = None
    frequency_penalty: float | None = None
    parallel_tool_calls: bool | None = None
    stream: bool | None = Field(
        None, description="Whether to stream response events as server-sent events."
    )
    stream_options: StreamOptionsParam | None = None
    background: bool | None = Field(
        None,
        description="Whether to run the request in the background and return immediately.",
    )
    max_output_tokens: conint(ge=16) | None = None
    max_tool_calls: conint(ge=1) | None = None
    reasoning: ReasoningParam | None = None
    safety_identifier: constr(max_length=64) | None = None
    prompt_cache_key: constr(max_length=64) | None = None
    truncation: TruncationEnum | None = None
    instructions: str | None = None
    store: bool | None = Field(
        None, description="Whether to store the response so it can be retrieved later."
    )
    service_tier: ServiceTierEnum | None = None
    top_logprobs: conint(ge=0, le=20) | None = None


class Message(BaseModel):
    type: Literal["message"] = Field(
        ..., description="The type of the message. Always set to `message`."
    )
    id: str = Field(..., description="The unique ID of the message.")
    status: MessageStatus
    role: MessageRole
    content: list[
        InputTextContent
        | OutputTextContent
        | TextContent
        | SummaryTextContent
        | ReasoningTextContent
        | RefusalContent
        | InputImageContent
        | InputFileContent
        | InputVideoContent
    ] = Field(..., description="The content of the message")


class GenericResponseItem(BaseModel):
    model_config = ConfigDict(extra="allow")

    type: str = Field(..., description="The output item type.")
    id: str | None = None
    status: str | None = None


class ItemField(
    RootModel[Message | FunctionCall | FunctionCallOutput | ReasoningBody | GenericResponseItem]
):
    root: Message | FunctionCall | FunctionCallOutput | ReasoningBody | GenericResponseItem = Field(
        ...,
        description="An item representing a message, tool call, tool output, reasoning, or other response element.",
    )


class ResponseResource(BaseModel):
    id: str = Field(..., description="The unique ID of the response that was created.")
    object: Literal["response"] = Field(
        ..., description="The object type, which was always `response`."
    )
    created_at: int = Field(
        ...,
        description="The Unix timestamp (in seconds) for when the response was created.",
    )
    completed_at: int | None
    status: str = Field(..., description="The status that was set for the response.")
    incomplete_details: IncompleteDetails | None
    model: str = Field(..., description="The model that generated this response.")
    previous_response_id: str | None
    instructions: str | None
    output: list[ItemField] = Field(
        ..., description="The output items that were generated by the model."
    )
    error: Error | None
    tools: list[Tool] = Field(
        ...,
        description="The tools that were available to the model during response generation.",
    )
    tool_choice: FunctionToolChoice | GenericToolChoice | ToolChoiceValueEnum | AllowedToolChoice
    truncation: TruncationEnum
    parallel_tool_calls: bool = Field(
        ...,
        description="Whether the model was allowed to call multiple tools in parallel.",
    )
    text: TextField
    top_p: float = Field(
        ...,
        description="The nucleus sampling parameter that was used for this response.",
    )
    presence_penalty: float = Field(
        ...,
        description="The presence penalty that was used to penalize new tokens based on whether they appear in the text so far.",
    )
    frequency_penalty: float = Field(
        ...,
        description="The frequency penalty that was used to penalize new tokens based on their frequency in the text so far.",
    )
    top_logprobs: int = Field(
        ...,
        description="The number of most likely tokens that were returned at each position, along with their log probabilities.",
    )
    temperature: float = Field(
        ..., description="The sampling temperature that was used for this response."
    )
    reasoning: Reasoning | None
    usage: Usage | None
    max_output_tokens: int | None
    max_tool_calls: int | None
    store: bool = Field(
        ...,
        description="Whether this response was stored so it can be retrieved later.",
    )
    background: bool = Field(..., description="Whether this request was run in the background.")
    service_tier: str = Field(..., description="The service tier that was used for this response.")
    metadata: Any = Field(
        ...,
        description="Developer-defined metadata that was associated with the response.",
    )
    safety_identifier: str | None
    prompt_cache_key: str | None


class ResponseCreatedStreamingEvent(BaseModel):
    type: Literal["response.created"] = Field(
        ..., description="The type of the event, always `response.created`."
    )
    sequence_number: int = Field(
        ..., description="The sequence number of the event that was emitted."
    )
    response: ResponseResource


class ResponseQueuedStreamingEvent(BaseModel):
    type: Literal["response.queued"] = Field(
        ..., description="The type of the event, always `response.queued`."
    )
    sequence_number: int = Field(
        ..., description="The sequence number of the event that was emitted."
    )
    response: ResponseResource


class ResponseInProgressStreamingEvent(BaseModel):
    type: Literal["response.in_progress"] = Field(
        ..., description="The type of the event, always `response.in_progress`."
    )
    sequence_number: int = Field(
        ..., description="The sequence number of the event that was emitted."
    )
    response: ResponseResource


class ResponseCompletedStreamingEvent(BaseModel):
    type: Literal["response.completed"] = Field(
        ..., description="The type of the event, always `response.completed`."
    )
    sequence_number: int = Field(
        ..., description="The sequence number of the event that was emitted."
    )
    response: ResponseResource


class ResponseFailedStreamingEvent(BaseModel):
    type: Literal["response.failed"] = Field(
        ..., description="The type of the event, always `response.failed`."
    )
    sequence_number: int = Field(
        ..., description="The sequence number of the event that was emitted."
    )
    response: ResponseResource


class ResponseIncompleteStreamingEvent(BaseModel):
    type: Literal["response.incomplete"] = Field(
        ..., description="The type of the event, always `response.incomplete`."
    )
    sequence_number: int = Field(
        ..., description="The sequence number of the event that was emitted."
    )
    response: ResponseResource


class Item2(Message, Item1):
    pass


class Item(RootModel[Item2 | Item3 | Item4 | Item5 | GenericResponseItem]):
    root: Item2 | Item3 | Item4 | Item5 | GenericResponseItem


class ResponseOutputItemAddedStreamingEvent(BaseModel):
    type: Literal["response.output_item.added"] = Field(
        ..., description="The type of the event, always `response.output_item.added`."
    )
    sequence_number: int = Field(
        ..., description="The sequence number of the event that was emitted."
    )
    output_index: int = Field(..., description="The index of the output item that was added.")
    item: Item | None


class Item62(Message, Item61):
    pass


class Item6(RootModel[Item62 | Item63 | Item64 | Item65 | GenericResponseItem]):
    root: Item62 | Item63 | Item64 | Item65 | GenericResponseItem


class ResponseOutputItemDoneStreamingEvent(BaseModel):
    type: Literal["response.output_item.done"] = Field(
        ..., description="The type of the event, always `response.output_item.done`."
    )
    sequence_number: int = Field(
        ..., description="The sequence number of the event that was emitted."
    )
    output_index: int = Field(..., description="The index of the output item that was completed.")
    item: Item6 | None
