/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/responses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create response
         * @description Creates a response.
         */
        post: operations["createResponse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Item reference
         * @description An internal identifier for an item to reference.
         */
        ItemReferenceParam: {
            type?: "item_reference" | null;
            /** @description The ID of the item to reference. */
            id: string;
        };
        ReasoningSummaryContentParam: {
            /**
             * @description The content type. Always `summary_text`.
             * @default summary_text
             * @enum {string}
             */
            type: "summary_text";
            /** @description The reasoning summary text. */
            text: string;
        };
        ReasoningItemParam: {
            id?: string | null;
            /**
             * @description The item type. Always `reasoning`.
             * @default reasoning
             * @enum {string}
             */
            type: "reasoning";
            /** @description Reasoning summary content associated with this item. */
            summary: components["schemas"]["ReasoningSummaryContentParam"][];
            content?: null;
            encrypted_content?: string | null;
        };
        /**
         * Input text
         * @description A text input to the model.
         */
        InputTextContentParam: {
            /**
             * @description The type of the input item. Always `input_text`.
             * @default input_text
             * @enum {string}
             */
            type: "input_text";
            /** @description The text input to the model. */
            text: string;
        };
        /** @enum {string} */
        DetailEnum: "low" | "high" | "auto";
        /**
         * Input image
         * @description An image input to the model. Learn about [image inputs](/docs/guides/vision)
         */
        InputImageContentParamAutoParam: {
            /**
             * @description The type of the input item. Always `input_image`.
             * @default input_image
             * @enum {string}
             */
            type: "input_image";
            image_url?: string | null;
            detail?: (components["schemas"]["ImageDetail"] & unknown) | null;
        };
        /**
         * Input file
         * @description A file input to the model.
         */
        InputFileContentParam: {
            /**
             * @description The type of the input item. Always `input_file`.
             * @default input_file
             * @enum {string}
             */
            type: "input_file";
            filename?: string | null;
            file_data?: string | null;
            file_url?: string | null;
        };
        UserMessageItemParam: {
            id?: string | null;
            /**
             * @description The item type. Always `message`.
             * @default message
             * @enum {string}
             */
            type: "message";
            /**
             * @description The message role. Always `user`.
             * @default user
             * @enum {string}
             */
            role: "user";
            /** @description The message content, as an array of content parts. */
            content: (components["schemas"]["InputTextContentParam"] | components["schemas"]["InputImageContentParamAutoParam"] | components["schemas"]["InputFileContentParam"])[] | string;
            status?: string | null;
        };
        SystemMessageItemParam: {
            id?: string | null;
            /**
             * @description The item type. Always `message`.
             * @default message
             * @enum {string}
             */
            type: "message";
            /**
             * @description The message role. Always `system`.
             * @default system
             * @enum {string}
             */
            role: "system";
            /** @description The message content, as an array of content parts. */
            content: components["schemas"]["InputTextContentParam"][] | string;
            status?: string | null;
        };
        DeveloperMessageItemParam: {
            id?: string | null;
            /**
             * @description The item type. Always `message`.
             * @default message
             * @enum {string}
             */
            type: "message";
            /**
             * @description The message role. Always `developer`.
             * @default developer
             * @enum {string}
             */
            role: "developer";
            /** @description The message content, as an array of content parts. */
            content: components["schemas"]["InputTextContentParam"][] | string;
            status?: string | null;
        };
        UrlCitationParam: {
            /**
             * @description The citation type. Always `url_citation`.
             * @default url_citation
             * @enum {string}
             */
            type: "url_citation";
            /** @description The index of the first character of the citation in the message. */
            start_index: number;
            /** @description The index of the last character of the citation in the message. */
            end_index: number;
            /** @description The URL of the cited resource. */
            url: string;
            /** @description The title of the cited resource. */
            title: string;
        };
        OutputTextContentParam: {
            /**
             * @description The content type. Always `output_text`.
             * @default output_text
             * @enum {string}
             */
            type: "output_text";
            /** @description The text content. */
            text: string;
            /** @description Citations associated with the text content. */
            annotations?: components["schemas"]["UrlCitationParam"][];
        };
        RefusalContentParam: {
            /**
             * @description The content type. Always `refusal`.
             * @default refusal
             * @enum {string}
             */
            type: "refusal";
            /** @description The refusal text. */
            refusal: string;
        };
        AssistantMessageItemParam: {
            id?: string | null;
            /**
             * @description The item type. Always `message`.
             * @default message
             * @enum {string}
             */
            type: "message";
            /**
             * @description The role of the message author. Always `assistant`.
             * @default assistant
             * @enum {string}
             */
            role: "assistant";
            /** @description The message content, as an array of content parts. */
            content: (components["schemas"]["OutputTextContentParam"] | components["schemas"]["RefusalContentParam"])[] | string;
            status?: string | null;
        };
        /** @enum {string} */
        FunctionCallItemStatus: "in_progress" | "completed" | "incomplete";
        FunctionCallItemParam: {
            id?: string | null;
            /** @description The unique ID of the function tool call generated by the model. */
            call_id: string;
            /**
             * @description The item type. Always `function_call`.
             * @default function_call
             * @enum {string}
             */
            type: "function_call";
            /** @description The name of the function to call. */
            name: string;
            /** @description The function arguments as a JSON string. */
            arguments: string;
            status?: (components["schemas"]["FunctionCallStatus"] & unknown) | null;
        };
        /**
         * Function tool call output
         * @description The output of a function tool call.
         */
        FunctionCallOutputItemParam: {
            id?: string | null;
            /** @description The unique ID of the function tool call generated by the model. */
            call_id: string;
            /**
             * @description The type of the function tool call output. Always `function_call_output`.
             * @default function_call_output
             * @enum {string}
             */
            type: "function_call_output";
            /** @description Text, image, or file output of the function tool call. */
            output: string | (components["schemas"]["InputTextContentParam"] | components["schemas"]["InputImageContentParamAutoParam"] | components["schemas"]["InputFileContentParam"] | components["schemas"]["InputVideoContent"])[];
            status?: (components["schemas"]["FunctionCallStatus"] & unknown) | null;
        };
        ItemParam: components["schemas"]["ItemReferenceParam"] | components["schemas"]["ReasoningItemParam"] | components["schemas"]["UserMessageItemParam"] | components["schemas"]["SystemMessageItemParam"] | components["schemas"]["DeveloperMessageItemParam"] | components["schemas"]["AssistantMessageItemParam"] | components["schemas"]["FunctionCallItemParam"] | components["schemas"]["FunctionCallOutputItemParam"];
        /** @enum {string} */
        IncludeEnum: "reasoning.encrypted_content" | "message.output_text.logprobs";
        EmptyModelParam: Record<string, never>;
        FunctionToolParam: {
            name: string;
            description?: string | null;
            parameters?: components["schemas"]["EmptyModelParam"] | null;
            strict?: boolean;
            /**
             * @default function
             * @enum {string}
             */
            type: "function";
        };
        ResponsesToolParam: components["schemas"]["FunctionToolParam"];
        SpecificFunctionParam: {
            /**
             * @description The tool to call. Always `function`.
             * @default function
             * @enum {string}
             */
            type: "function";
            /** @description The name of the function tool to call. */
            name: string;
        };
        SpecificToolChoiceParam: components["schemas"]["SpecificFunctionParam"];
        /** @enum {string} */
        ToolChoiceValueEnum: "none" | "auto" | "required";
        AllowedToolsParam: {
            /**
             * @description The tool choice type. Always `allowed_tools`.
             * @default allowed_tools
             * @enum {string}
             */
            type: "allowed_tools";
            /** @description The list of tools that are permitted for this request. */
            tools: components["schemas"]["SpecificToolChoiceParam"][];
            mode?: components["schemas"]["ToolChoiceValueEnum"] & unknown;
        };
        /** @description Controls which tool the model should use, if any. */
        ToolChoiceParam: components["schemas"]["SpecificToolChoiceParam"] | components["schemas"]["ToolChoiceValueEnum"] | components["schemas"]["AllowedToolsParam"];
        /**
         * @description Set of 16 key-value pairs that can be attached to an object. This can be         useful for storing additional information about the object in a structured         format, and querying for objects via API or the dashboard.
         *             Keys are strings with a maximum length of 64 characters. Values are strings         with a maximum length of 512 characters.
         */
        MetadataParam: {
            [key: string]: string;
        };
        /** @enum {string} */
        VerbosityEnum: "low" | "medium" | "high";
        TextParam: {
            /** @description The format configuration for text output. */
            format?: components["schemas"]["TextFormatParam"] | null;
            verbosity?: components["schemas"]["VerbosityEnum"] & unknown;
        };
        /** @description Options that control streamed response behavior. */
        StreamOptionsParam: {
            /** @description Whether to obfuscate sensitive information in streamed output. Defaults to `true`. */
            include_obfuscation?: boolean;
        };
        /** @enum {string} */
        ReasoningEffortEnum: "none" | "low" | "medium" | "high" | "xhigh";
        /** @enum {string} */
        ReasoningSummaryEnum: "concise" | "detailed" | "auto";
        /** @description **gpt-5 and o-series models only** Configuration options for [reasoning models](https://platform.openai.com/docs/guides/reasoning). */
        ReasoningParam: {
            effort?: components["schemas"]["ReasoningEffortEnum"] | null;
            summary?: (components["schemas"]["ReasoningSummaryEnum"] & unknown) | null;
        };
        /** @enum {string} */
        TruncationEnum: "auto" | "disabled";
        /** @enum {string} */
        ServiceTierEnum: "auto" | "default" | "flex" | "priority";
        CreateResponseBody: {
            model?: string | null;
            input?: (string | components["schemas"]["ItemParam"][]) | null;
            previous_response_id?: string | null;
            include?: components["schemas"]["IncludeEnum"][];
            tools?: components["schemas"]["ResponsesToolParam"][] | null;
            tool_choice?: (components["schemas"]["ToolChoiceParam"] & unknown) | null;
            metadata?: (components["schemas"]["MetadataParam"] & unknown) | null;
            text?: (components["schemas"]["TextParam"] & unknown) | null;
            temperature?: number | null;
            top_p?: number | null;
            presence_penalty?: number | null;
            frequency_penalty?: number | null;
            parallel_tool_calls?: boolean | null;
            /** @description Whether to stream response events as server-sent events. */
            stream?: boolean;
            stream_options?: (components["schemas"]["StreamOptionsParam"] & unknown) | null;
            /** @description Whether to run the request in the background and return immediately. */
            background?: boolean;
            max_output_tokens?: number | null;
            max_tool_calls?: number | null;
            reasoning?: (components["schemas"]["ReasoningParam"] & unknown) | null;
            safety_identifier?: string | null;
            prompt_cache_key?: string | null;
            truncation?: components["schemas"]["TruncationEnum"] & unknown;
            instructions?: string | null;
            /** @description Whether to store the response so it can be retrieved later. */
            store?: boolean;
            service_tier?: components["schemas"]["ServiceTierEnum"] & unknown;
            top_logprobs?: number | null;
        };
        /**
         * Incomplete details
         * @description Details about why the response was incomplete.
         */
        IncompleteDetails: {
            /** @description The reason the response could not be completed. */
            reason: string;
        };
        /** @enum {string} */
        MessageRole: "user" | "assistant" | "system" | "developer";
        /**
         * Input text
         * @description A text input to the model.
         */
        InputTextContent: {
            /**
             * @description The type of the input item. Always `input_text`.
             * @default input_text
             * @enum {string}
             */
            type: "input_text";
            /** @description The text input to the model. */
            text: string;
        };
        /**
         * URL citation
         * @description A citation for a web resource used to generate a model response.
         */
        UrlCitationBody: {
            /**
             * @description The type of the URL citation. Always `url_citation`.
             * @default url_citation
             * @enum {string}
             */
            type: "url_citation";
            /** @description The URL of the web resource. */
            url: string;
            /** @description The index of the first character of the URL citation in the message. */
            start_index: number;
            /** @description The index of the last character of the URL citation in the message. */
            end_index: number;
            /** @description The title of the web resource. */
            title: string;
        };
        /** @description An annotation that applies to a span of output text. */
        Annotation: components["schemas"]["UrlCitationBody"];
        /**
         * Top log probability
         * @description The top log probability of a token.
         */
        TopLogProb: {
            token: string;
            logprob: number;
            bytes: number[];
        };
        /**
         * Log probability
         * @description The log probability of a token.
         */
        LogProb: {
            token: string;
            logprob: number;
            bytes: number[];
            top_logprobs: components["schemas"]["TopLogProb"][];
        };
        /**
         * Output text
         * @description A text output from the model.
         */
        OutputTextContent: {
            /**
             * @description The type of the output text. Always `output_text`.
             * @default output_text
             * @enum {string}
             */
            type: "output_text";
            /** @description The text output from the model. */
            text: string;
            /** @description The annotations of the text output. */
            annotations: components["schemas"]["Annotation"][];
            logprobs?: components["schemas"]["LogProb"][];
        };
        /**
         * Text Content
         * @description A text content.
         */
        TextContent: {
            /**
             * @default text
             * @enum {string}
             */
            type: "text";
            text: string;
        };
        /**
         * Summary text
         * @description A summary text from the model.
         */
        SummaryTextContent: {
            /**
             * @description The type of the object. Always `summary_text`.
             * @default summary_text
             * @enum {string}
             */
            type: "summary_text";
            /** @description A summary of the reasoning output from the model so far. */
            text: string;
        };
        /**
         * Reasoning text
         * @description Reasoning text from the model.
         */
        ReasoningTextContent: {
            /**
             * @description The type of the reasoning text. Always `reasoning_text`.
             * @default reasoning_text
             * @enum {string}
             */
            type: "reasoning_text";
            /** @description The reasoning text from the model. */
            text: string;
        };
        /**
         * Refusal
         * @description A refusal from the model.
         */
        RefusalContent: {
            /**
             * @description The type of the refusal. Always `refusal`.
             * @default refusal
             * @enum {string}
             */
            type: "refusal";
            /** @description The refusal explanation from the model. */
            refusal: string;
        };
        /** @enum {string} */
        ImageDetail: "low" | "high" | "auto";
        /**
         * Input image
         * @description An image input to the model. Learn about [image inputs](/docs/guides/vision).
         */
        InputImageContent: {
            /**
             * @description The type of the input item. Always `input_image`.
             * @default input_image
             * @enum {string}
             */
            type: "input_image";
            image_url: string | null;
            detail: components["schemas"]["ImageDetail"] & unknown;
        };
        /**
         * Input file
         * @description A file input to the model.
         */
        InputFileContent: {
            /**
             * @description The type of the input item. Always `input_file`.
             * @default input_file
             * @enum {string}
             */
            type: "input_file";
            /** @description The name of the file to be sent to the model. */
            filename?: string;
            /** @description The URL of the file to be sent to the model. */
            file_url?: string;
        };
        /** @enum {string} */
        MessageStatus: "in_progress" | "completed" | "incomplete";
        /**
         * Message
         * @description A message to or from the model.
         */
        Message: {
            /**
             * @description The type of the message. Always set to `message`.
             * @default message
             * @enum {string}
             */
            type: "message";
            /** @description The unique ID of the message. */
            id: string;
            status: components["schemas"]["MessageStatus"] & unknown;
            role: components["schemas"]["MessageRole"] & unknown;
            /** @description The content of the message */
            content: (components["schemas"]["InputTextContent"] | components["schemas"]["OutputTextContent"] | components["schemas"]["TextContent"] | components["schemas"]["SummaryTextContent"] | components["schemas"]["ReasoningTextContent"] | components["schemas"]["RefusalContent"] | components["schemas"]["InputImageContent"] | components["schemas"]["InputFileContent"] | components["schemas"]["InputVideoContent"])[];
        };
        /** @enum {string} */
        FunctionCallStatus: "in_progress" | "completed" | "incomplete";
        /**
         * Function call
         * @description A function tool call that was generated by the model.
         */
        FunctionCall: {
            /**
             * @description The type of the item. Always `function_call`.
             * @default function_call
             * @enum {string}
             */
            type: "function_call";
            /** @description The unique ID of the function call item. */
            id: string;
            /** @description The unique ID of the function tool call that was generated. */
            call_id: string;
            /** @description The name of the function that was called. */
            name: string;
            /** @description The arguments JSON string that was generated. */
            arguments: string;
            status: components["schemas"]["FunctionCallStatus"] & unknown;
        };
        /**
         * @description Similar to `FunctionCallStatus`. All three options are allowed here for compatibility, but because in practice these items will be provided by developers, only `completed` should be used.
         * @enum {string}
         */
        FunctionCallOutputStatusEnum: "in_progress" | "completed" | "incomplete";
        /**
         * Function call output
         * @description A function tool call output that was returned by the tool.
         */
        FunctionCallOutput: {
            /**
             * @description The type of the function tool call output. Always `function_call_output`.
             * @default function_call_output
             * @enum {string}
             */
            type: "function_call_output";
            /** @description The unique ID of the function tool call output. Populated when this item is returned via API. */
            id: string;
            /** @description The unique ID of the function tool call generated by the model. */
            call_id: string;
            output: string | (components["schemas"]["InputTextContent"] | components["schemas"]["InputImageContent"] | components["schemas"]["InputFileContent"])[];
            status: components["schemas"]["FunctionCallOutputStatusEnum"] & unknown;
        };
        /**
         * Reasoning item
         * @description A reasoning item that was generated by the model.
         */
        ReasoningBody: {
            /**
             * @description The type of the item. Always `reasoning`.
             * @default reasoning
             * @enum {string}
             */
            type: "reasoning";
            /** @description The unique ID of the reasoning item. */
            id: string;
            /** @description The reasoning content that was generated. */
            content?: (components["schemas"]["InputTextContent"] | components["schemas"]["OutputTextContent"] | components["schemas"]["TextContent"] | components["schemas"]["SummaryTextContent"] | components["schemas"]["ReasoningTextContent"] | components["schemas"]["RefusalContent"] | components["schemas"]["InputImageContent"] | components["schemas"]["InputFileContent"])[];
            /** @description The reasoning summary content that was generated. */
            summary: (components["schemas"]["InputTextContent"] | components["schemas"]["OutputTextContent"] | components["schemas"]["TextContent"] | components["schemas"]["SummaryTextContent"] | components["schemas"]["ReasoningTextContent"] | components["schemas"]["RefusalContent"] | components["schemas"]["InputImageContent"] | components["schemas"]["InputFileContent"])[];
            /** @description The encrypted reasoning content that was generated. */
            encrypted_content?: string;
        };
        /** @description An item representing a message, tool call, tool output, reasoning, or other response element. */
        ItemField: components["schemas"]["Message"] | components["schemas"]["FunctionCall"] | components["schemas"]["FunctionCallOutput"] | components["schemas"]["ReasoningBody"];
        /**
         * Error
         * @description An error that occurred while generating the response.
         */
        Error: {
            /** @description A machine-readable error code that was returned. */
            code: string;
            /** @description A human-readable description of the error that was returned. */
            message: string;
        };
        /**
         * Function
         * @description Defines a function in your own code the model can choose to call. Learn more about [function calling](https://platform.openai.com/docs/guides/function-calling).
         */
        FunctionTool: {
            /**
             * @description The type of the function tool. Always `function`.
             * @default function
             * @enum {string}
             */
            type: "function";
            /** @description The name of the function to call. */
            name: string;
            description: string | null;
            parameters: {
                [key: string]: unknown;
            } | null;
            strict: boolean | null;
        };
        /** @description A tool that can be used to generate a response. */
        Tool: components["schemas"]["FunctionTool"];
        FunctionToolChoice: {
            /**
             * @default function
             * @enum {string}
             */
            type: "function";
            name?: string;
        };
        AllowedToolChoice: {
            /**
             * @default allowed_tools
             * @enum {string}
             */
            type: "allowed_tools";
            tools: components["schemas"]["FunctionToolChoice"][];
            mode: components["schemas"]["ToolChoiceValueEnum"];
        };
        TextResponseFormat: {
            /**
             * @default text
             * @enum {string}
             */
            type: "text";
        };
        JsonObjectResponseFormat: {
            /**
             * @default json_object
             * @enum {string}
             */
            type: "json_object";
        };
        JsonSchemaResponseFormat: {
            /**
             * @default json_schema
             * @enum {string}
             */
            type: "json_schema";
            name: string;
            description: string | null;
            schema: null;
            strict: boolean;
        };
        TextField: {
            format: components["schemas"]["TextResponseFormat"] | components["schemas"]["JsonObjectResponseFormat"] | components["schemas"]["JsonSchemaResponseFormat"];
            verbosity?: components["schemas"]["VerbosityEnum"];
        };
        /**
         * Reasoning
         * @description Reasoning configuration and metadata that were used for the response.
         */
        Reasoning: {
            effort: components["schemas"]["ReasoningEffortEnum"] | null;
            summary: (components["schemas"]["ReasoningSummaryEnum"] & unknown) | null;
        };
        /**
         * Input tokens details
         * @description A breakdown of input token usage that was recorded.
         */
        InputTokensDetails: {
            /** @description The number of input tokens that were served from cache. */
            cached_tokens: number;
        };
        /**
         * Output tokens details
         * @description A breakdown of output token usage that was recorded.
         */
        OutputTokensDetails: {
            /** @description The number of output tokens that were attributed to reasoning. */
            reasoning_tokens: number;
        };
        /**
         * Usage
         * @description Token usage statistics that were recorded for the response.
         */
        Usage: {
            /** @description The number of input tokens that were used to generate the response. */
            input_tokens: number;
            /** @description The number of output tokens that were generated by the model. */
            output_tokens: number;
            /** @description The total number of tokens that were used. */
            total_tokens: number;
            input_tokens_details: components["schemas"]["InputTokensDetails"] & unknown;
            output_tokens_details: components["schemas"]["OutputTokensDetails"] & unknown;
        };
        /**
         * The response object
         * @description The complete response object that was returned by the Responses API.
         * @example {
         *       "id": "resp_67ccd3a9da748190baa7f1570fe91ac604becb25c45c1d41",
         *       "object": "response",
         *       "created_at": 1741476777,
         *       "status": "completed",
         *       "completed_at": 1741476778,
         *       "model": "gpt-4o-2024-08-06",
         *       "output": [
         *         {
         *           "type": "message",
         *           "id": "msg_67ccd3acc8d48190a77525dc6de64b4104becb25c45c1d41",
         *           "status": "completed",
         *           "role": "assistant",
         *           "content": [
         *             {
         *               "type": "output_text",
         *               "text": "The image depicts a scenic landscape with a wooden boardwalk or pathway leading through lush, green grass under a blue sky with some clouds. The setting suggests a peaceful natural area, possibly a park or nature reserve. There are trees and shrubs in the background.",
         *               "annotations": []
         *             }
         *           ]
         *         }
         *       ],
         *       "parallel_tool_calls": true,
         *       "reasoning": {},
         *       "store": true,
         *       "background": false,
         *       "temperature": 1,
         *       "presence_penalty": 0,
         *       "frequency_penalty": 0,
         *       "text": {
         *         "format": {
         *           "type": "text"
         *         }
         *       },
         *       "tool_choice": "auto",
         *       "tools": [],
         *       "top_p": 1,
         *       "truncation": "disabled",
         *       "usage": {
         *         "input_tokens": 328,
         *         "input_tokens_details": {
         *           "cached_tokens": 0
         *         },
         *         "output_tokens": 52,
         *         "output_tokens_details": {
         *           "reasoning_tokens": 0
         *         },
         *         "total_tokens": 380
         *       },
         *       "metadata": {},
         *       "service_tier": "default",
         *       "top_logprobs": 0
         *     }
         */
        ResponseResource: {
            /** @description The unique ID of the response that was created. */
            id: string;
            /**
             * @description The object type, which was always `response`.
             * @default response
             * @enum {string}
             */
            object: "response";
            /** @description The Unix timestamp (in seconds) for when the response was created. */
            created_at: number;
            completed_at: number | null;
            /** @description The status that was set for the response. */
            status: string;
            incomplete_details: (components["schemas"]["IncompleteDetails"] & unknown) | null;
            /** @description The model that generated this response. */
            model: string;
            previous_response_id: string | null;
            instructions: string | null;
            /** @description The output items that were generated by the model. */
            output: components["schemas"]["ItemField"][];
            error: (components["schemas"]["Error"] & unknown) | null;
            /** @description The tools that were available to the model during response generation. */
            tools: components["schemas"]["Tool"][];
            tool_choice: components["schemas"]["FunctionToolChoice"] | components["schemas"]["ToolChoiceValueEnum"] | components["schemas"]["AllowedToolChoice"];
            truncation: components["schemas"]["TruncationEnum"] & unknown;
            /** @description Whether the model was allowed to call multiple tools in parallel. */
            parallel_tool_calls: boolean;
            text: components["schemas"]["TextField"] & unknown;
            /** @description The nucleus sampling parameter that was used for this response. */
            top_p: number;
            /** @description The presence penalty that was used to penalize new tokens based on whether they appear in the text so far. */
            presence_penalty: number;
            /** @description The frequency penalty that was used to penalize new tokens based on their frequency in the text so far. */
            frequency_penalty: number;
            /** @description The number of most likely tokens that were returned at each position, along with their log probabilities. */
            top_logprobs: number;
            /** @description The sampling temperature that was used for this response. */
            temperature: number;
            reasoning: (components["schemas"]["Reasoning"] & unknown) | null;
            usage: (components["schemas"]["Usage"] & unknown) | null;
            max_output_tokens: number | null;
            max_tool_calls: number | null;
            /** @description Whether this response was stored so it can be retrieved later. */
            store: boolean;
            /** @description Whether this request was run in the background. */
            background: boolean;
            /** @description The service tier that was used for this response. */
            service_tier: string;
            /** @description Developer-defined metadata that was associated with the response. */
            metadata: unknown;
            safety_identifier: string | null;
            prompt_cache_key: string | null;
        };
        /**
         * Response created event
         * @description A streaming event that indicated the response was created.
         */
        ResponseCreatedStreamingEvent: {
            /**
             * @description The type of the event, always `response.created`.
             * @default response.created
             * @enum {string}
             */
            type: "response.created";
            /** @description The sequence number of the event that was emitted. */
            sequence_number: number;
            response: components["schemas"]["ResponseResource"] & unknown;
        };
        /**
         * Response queued event
         * @description A streaming event that indicated the response was queued.
         */
        ResponseQueuedStreamingEvent: {
            /**
             * @description The type of the event, always `response.queued`.
             * @default response.queued
             * @enum {string}
             */
            type: "response.queued";
            /** @description The sequence number of the event that was emitted. */
            sequence_number: number;
            response: components["schemas"]["ResponseResource"] & unknown;
        };
        /**
         * Response in progress event
         * @description A streaming event that indicated the response was in progress.
         */
        ResponseInProgressStreamingEvent: {
            /**
             * @description The type of the event, always `response.in_progress`.
             * @default response.in_progress
             * @enum {string}
             */
            type: "response.in_progress";
            /** @description The sequence number of the event that was emitted. */
            sequence_number: number;
            response: components["schemas"]["ResponseResource"] & unknown;
        };
        /**
         * Response completed event
         * @description A streaming event that indicated the response was completed.
         */
        ResponseCompletedStreamingEvent: {
            /**
             * @description The type of the event, always `response.completed`.
             * @default response.completed
             * @enum {string}
             */
            type: "response.completed";
            /** @description The sequence number of the event that was emitted. */
            sequence_number: number;
            response: components["schemas"]["ResponseResource"] & unknown;
        };
        /**
         * Response failed event
         * @description A streaming event that indicated the response had failed.
         */
        ResponseFailedStreamingEvent: {
            /**
             * @description The type of the event, always `response.failed`.
             * @default response.failed
             * @enum {string}
             */
            type: "response.failed";
            /** @description The sequence number of the event that was emitted. */
            sequence_number: number;
            response: components["schemas"]["ResponseResource"] & unknown;
        };
        /**
         * Response incomplete event
         * @description A streaming event that indicated the response was incomplete.
         */
        ResponseIncompleteStreamingEvent: {
            /**
             * @description The type of the event, always `response.incomplete`.
             * @default response.incomplete
             * @enum {string}
             */
            type: "response.incomplete";
            /** @description The sequence number of the event that was emitted. */
            sequence_number: number;
            response: components["schemas"]["ResponseResource"] & unknown;
        };
        /**
         * Response output item added event
         * @description A streaming event that indicated an output item was added to the response.
         */
        ResponseOutputItemAddedStreamingEvent: {
            /**
             * @description The type of the event, always `response.output_item.added`.
             * @default response.output_item.added
             * @enum {string}
             */
            type: "response.output_item.added";
            /** @description The sequence number of the event that was emitted. */
            sequence_number: number;
            /** @description The index of the output item that was added. */
            output_index: number;
            item: (components["schemas"]["ItemField"] & unknown) | null;
        };
        /**
         * Response output item done event
         * @description A streaming event that indicated an output item was completed.
         */
        ResponseOutputItemDoneStreamingEvent: {
            /**
             * @description The type of the event, always `response.output_item.done`.
             * @default response.output_item.done
             * @enum {string}
             */
            type: "response.output_item.done";
            /** @description The sequence number of the event that was emitted. */
            sequence_number: number;
            /** @description The index of the output item that was completed. */
            output_index: number;
            item: (components["schemas"]["ItemField"] & unknown) | null;
        };
        /**
         * Response reasoning summary part added event
         * @description A streaming event that indicated a reasoning summary part was added.
         */
        ResponseReasoningSummaryPartAddedStreamingEvent: {
            /**
             * @description The type of the event, always `response.reasoning_summary_part.added`.
             * @default response.reasoning_summary_part.added
             * @enum {string}
             */
            type: "response.reasoning_summary_part.added";
            /** @description The sequence number of the event that was emitted. */
            sequence_number: number;
            /** @description The ID of the item that was updated. */
            item_id: string;
            /** @description The index of the output item that was updated. */
            output_index: number;
            /** @description The index of the summary part that was added. */
            summary_index: number;
            /** @description A content part that makes up an input or output item. */
            part: components["schemas"]["InputTextContent"] | components["schemas"]["OutputTextContent"] | components["schemas"]["TextContent"] | components["schemas"]["SummaryTextContent"] | components["schemas"]["ReasoningTextContent"] | components["schemas"]["RefusalContent"] | components["schemas"]["InputImageContent"] | components["schemas"]["InputFileContent"];
        };
        /**
         * Response reasoning summary part done event
         * @description A streaming event that indicated a reasoning summary part was completed.
         */
        ResponseReasoningSummaryPartDoneStreamingEvent: {
            /**
             * @description The type of the event, always `response.reasoning_summary_part.done`.
             * @default response.reasoning_summary_part.done
             * @enum {string}
             */
            type: "response.reasoning_summary_part.done";
            /** @description The sequence number of the event that was emitted. */
            sequence_number: number;
            /** @description The ID of the item that was updated. */
            item_id: string;
            /** @description The index of the output item that was updated. */
            output_index: number;
            /** @description The index of the summary part that was completed. */
            summary_index: number;
            /** @description A content part that makes up an input or output item. */
            part: components["schemas"]["InputTextContent"] | components["schemas"]["OutputTextContent"] | components["schemas"]["TextContent"] | components["schemas"]["SummaryTextContent"] | components["schemas"]["ReasoningTextContent"] | components["schemas"]["RefusalContent"] | components["schemas"]["InputImageContent"] | components["schemas"]["InputFileContent"];
        };
        /**
         * Response content part added event
         * @description A streaming event that indicated a content part was added.
         */
        ResponseContentPartAddedStreamingEvent: {
            /**
             * @description The type of the event, always `response.content_part.added`.
             * @default response.content_part.added
             * @enum {string}
             */
            type: "response.content_part.added";
            /** @description The sequence number of the event that was emitted. */
            sequence_number: number;
            /** @description The ID of the item that was updated. */
            item_id: string;
            /** @description The index of the output item that was updated. */
            output_index: number;
            /** @description The index of the content part that was added. */
            content_index: number;
            /** @description A content part that makes up an input or output item. */
            part: components["schemas"]["InputTextContent"] | components["schemas"]["OutputTextContent"] | components["schemas"]["TextContent"] | components["schemas"]["SummaryTextContent"] | components["schemas"]["ReasoningTextContent"] | components["schemas"]["RefusalContent"] | components["schemas"]["InputImageContent"] | components["schemas"]["InputFileContent"];
        };
        /**
         * Response content part done event
         * @description A streaming event that indicated a content part was completed.
         */
        ResponseContentPartDoneStreamingEvent: {
            /**
             * @description The type of the event, always `response.content_part.done`.
             * @default response.content_part.done
             * @enum {string}
             */
            type: "response.content_part.done";
            /** @description The sequence number of the event that was emitted. */
            sequence_number: number;
            /** @description The ID of the item that was updated. */
            item_id: string;
            /** @description The index of the output item that was updated. */
            output_index: number;
            /** @description The index of the content part that was completed. */
            content_index: number;
            /** @description A content part that makes up an input or output item. */
            part: components["schemas"]["InputTextContent"] | components["schemas"]["OutputTextContent"] | components["schemas"]["TextContent"] | components["schemas"]["SummaryTextContent"] | components["schemas"]["ReasoningTextContent"] | components["schemas"]["RefusalContent"] | components["schemas"]["InputImageContent"] | components["schemas"]["InputFileContent"];
        };
        /**
         * Response output text delta event
         * @description A streaming event that indicated output text was incrementally added.
         */
        ResponseOutputTextDeltaStreamingEvent: {
            /**
             * @description The type of the event, always `response.output_text.delta`.
             * @default response.output_text.delta
             * @enum {string}
             */
            type: "response.output_text.delta";
            /** @description The sequence number of the event that was emitted. */
            sequence_number: number;
            /** @description The ID of the item that was updated. */
            item_id: string;
            /** @description The index of the output item that was updated. */
            output_index: number;
            /** @description The index of the content part that was updated. */
            content_index: number;
            /** @description The text delta that was appended. */
            delta: string;
            /** @description The token log probabilities that were emitted with the delta, if any. */
            logprobs?: components["schemas"]["LogProb"][];
            /** @description An obfuscation string that was added to pad the event payload. */
            obfuscation?: string;
        };
        /**
         * Response output text done event
         * @description A streaming event that indicated output text was completed.
         */
        ResponseOutputTextDoneStreamingEvent: {
            /**
             * @description The type of the event, always `response.output_text.done`.
             * @default response.output_text.done
             * @enum {string}
             */
            type: "response.output_text.done";
            /** @description The sequence number of the event that was emitted. */
            sequence_number: number;
            /** @description The ID of the item that was updated. */
            item_id: string;
            /** @description The index of the output item that was updated. */
            output_index: number;
            /** @description The index of the content part that was completed. */
            content_index: number;
            /** @description The final text that was emitted. */
            text: string;
            /** @description The token log probabilities that were emitted with the final text, if any. */
            logprobs?: components["schemas"]["LogProb"][];
        };
        /**
         * Response refusal delta event
         * @description A streaming event that indicated refusal text was incrementally added.
         */
        ResponseRefusalDeltaStreamingEvent: {
            /**
             * @description The type of the event, always `response.refusal.delta`.
             * @default response.refusal.delta
             * @enum {string}
             */
            type: "response.refusal.delta";
            /** @description The sequence number of the event that was emitted. */
            sequence_number: number;
            /** @description The ID of the item that was updated. */
            item_id: string;
            /** @description The index of the output item that was updated. */
            output_index: number;
            /** @description The index of the refusal content that was updated. */
            content_index: number;
            /** @description The refusal text delta that was appended. */
            delta: string;
        };
        /**
         * Response refusal done event
         * @description A streaming event that indicated refusal text was completed.
         */
        ResponseRefusalDoneStreamingEvent: {
            /**
             * @description The type of the event, always `response.refusal.done`.
             * @default response.refusal.done
             * @enum {string}
             */
            type: "response.refusal.done";
            /** @description The sequence number of the event that was emitted. */
            sequence_number: number;
            /** @description The ID of the item that was updated. */
            item_id: string;
            /** @description The index of the output item that was updated. */
            output_index: number;
            /** @description The index of the refusal content that was completed. */
            content_index: number;
            /** @description The final refusal text that was emitted. */
            refusal: string;
        };
        /**
         * Response reasoning delta event
         * @description A streaming event that indicated reasoning text was incrementally added.
         */
        ResponseReasoningDeltaStreamingEvent: {
            /**
             * @description The type of the event, always `response.reasoning.delta`.
             * @default response.reasoning.delta
             * @enum {string}
             */
            type: "response.reasoning.delta";
            /** @description The sequence number of the event that was emitted. */
            sequence_number: number;
            /** @description The ID of the item that was updated. */
            item_id: string;
            /** @description The index of the output item that was updated. */
            output_index: number;
            /** @description The index of the reasoning content that was updated. */
            content_index: number;
            /** @description The reasoning text delta that was appended. */
            delta: string;
            /** @description An obfuscation string that was added to pad the event payload. */
            obfuscation?: string;
        };
        /**
         * Response reasoning done event
         * @description A streaming event that indicated reasoning text was completed.
         */
        ResponseReasoningDoneStreamingEvent: {
            /**
             * @description The type of the event, always `response.reasoning.done`.
             * @default response.reasoning.done
             * @enum {string}
             */
            type: "response.reasoning.done";
            /** @description The sequence number of the event that was emitted. */
            sequence_number: number;
            /** @description The ID of the item that was updated. */
            item_id: string;
            /** @description The index of the output item that was updated. */
            output_index: number;
            /** @description The index of the reasoning content that was completed. */
            content_index: number;
            /** @description The final reasoning text that was emitted. */
            text: string;
        };
        /**
         * Response reasoning summary delta event
         * @description A streaming event that indicated a reasoning summary was incrementally added.
         */
        ResponseReasoningSummaryDeltaStreamingEvent: {
            /**
             * @description The type of the event, always `response.reasoning_summary.delta`.
             * @default response.reasoning_summary_text.delta
             * @enum {string}
             */
            type: "response.reasoning_summary_text.delta";
            /** @description The sequence number of the event that was emitted. */
            sequence_number: number;
            /** @description The ID of the item that was updated. */
            item_id: string;
            /** @description The index of the output item that was updated. */
            output_index: number;
            /** @description The index of the summary content that was updated. */
            summary_index: number;
            /** @description The summary text delta that was appended. */
            delta: string;
            /** @description An obfuscation string that was added to pad the event payload. */
            obfuscation?: string;
        };
        /**
         * Response reasoning summary done event
         * @description A streaming event that indicated a reasoning summary was completed.
         */
        ResponseReasoningSummaryDoneStreamingEvent: {
            /**
             * @description The type of the event, always `response.reasoning_summary.done`.
             * @default response.reasoning_summary_text.done
             * @enum {string}
             */
            type: "response.reasoning_summary_text.done";
            /** @description The sequence number of the event that was emitted. */
            sequence_number: number;
            /** @description The ID of the item that was updated. */
            item_id: string;
            /** @description The index of the output item that was updated. */
            output_index: number;
            /** @description The index of the summary content that was completed. */
            summary_index: number;
            /** @description The final summary text that was emitted. */
            text: string;
        };
        /**
         * Response output text annotation added event
         * @description A streaming event that indicated an output text annotation was added.
         */
        ResponseOutputTextAnnotationAddedStreamingEvent: {
            /**
             * @description The type of the event, always `response.output_text.annotation.added`.
             * @default response.output_text.annotation.added
             * @enum {string}
             */
            type: "response.output_text.annotation.added";
            /** @description The sequence number of the event that was emitted. */
            sequence_number: number;
            /** @description The ID of the item that was updated. */
            item_id: string;
            /** @description The index of the output item that was updated. */
            output_index: number;
            /** @description The index of the output text content that was updated. */
            content_index: number;
            /** @description The index of the annotation that was added. */
            annotation_index: number;
            annotation: (components["schemas"]["Annotation"] & unknown) | null;
        };
        /**
         * Response function call arguments delta event
         * @description A streaming event that indicated function call arguments were incrementally added.
         */
        ResponseFunctionCallArgumentsDeltaStreamingEvent: {
            /**
             * @description The type of the event, always `response.function_call_arguments.delta`.
             * @default response.function_call_arguments.delta
             * @enum {string}
             */
            type: "response.function_call_arguments.delta";
            /** @description The sequence number of the event that was emitted. */
            sequence_number: number;
            /** @description The ID of the tool call item that was updated. */
            item_id: string;
            /** @description The index of the output item that was updated. */
            output_index: number;
            /** @description The arguments delta that was appended. */
            delta: string;
            /** @description An obfuscation string that was added to pad the event payload. */
            obfuscation?: string;
        };
        /**
         * Response function call arguments done event
         * @description A streaming event that indicated function call arguments were completed.
         */
        ResponseFunctionCallArgumentsDoneStreamingEvent: {
            /**
             * @description The type of the event, always `response.function_call_arguments.done`.
             * @default response.function_call_arguments.done
             * @enum {string}
             */
            type: "response.function_call_arguments.done";
            /** @description The sequence number of the event that was emitted. */
            sequence_number: number;
            /** @description The ID of the tool call item that was updated. */
            item_id: string;
            /** @description The index of the output item that was updated. */
            output_index: number;
            /** @description The final arguments string that was emitted. */
            arguments: string;
        };
        /**
         * Error payload
         * @description An error payload that was emitted for a streaming error event.
         */
        ErrorPayload: {
            /** @description The error type that was emitted. */
            type: string;
            code: string | null;
            /** @description The human-readable error message that was emitted. */
            message: string;
            param: string | null;
            /** @description The response headers that were emitted with the error, if any. */
            headers?: {
                [key: string]: string;
            };
        };
        /**
         * Error event
         * @description A streaming event that indicated an error was emitted.
         */
        ErrorStreamingEvent: {
            /**
             * @description The type of the event, always `error`.
             * @default error
             * @enum {string}
             */
            type: "error";
            /** @description The sequence number of the event that was emitted. */
            sequence_number: number;
            error: components["schemas"]["ErrorPayload"] & unknown;
        };
        /** @description A content block representing a video input to the model. */
        InputVideoContent: {
            /**
             * @description The type of the input content. Always `input_video`.
             * @enum {string}
             */
            type: "input_video";
            /** @description A base64 or remote url that resolves to a video file. */
            video_url: string;
        };
        JsonSchemaResponseFormatParam: {
            /**
             * @description The type of response format being defined. Always `json_schema`.
             * @enum {string}
             */
            type?: "json_schema";
            /**
             * @description A description of what the response format is for, used by the model to
             *     determine how to respond in the format.
             */
            description?: string;
            /**
             * @description The name of the response format. Must be a-z, A-Z, 0-9, or contain
             *     underscores and dashes, with a maximum length of 64.
             */
            name?: string;
            /**
             * JSON schema
             * @description The schema for the response format, described as a JSON Schema object.
             */
            schema?: {
                [key: string]: unknown;
            };
            strict?: boolean | null;
        };
        TextFormatParam: components["schemas"]["TextResponseFormat"] | components["schemas"]["JsonSchemaResponseFormatParam"];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createResponse: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateResponseBody"];
                "application/x-www-form-urlencoded": components["schemas"]["CreateResponseBody"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseResource"];
                    "text/event-stream": components["schemas"]["ResponseCreatedStreamingEvent"] | components["schemas"]["ResponseQueuedStreamingEvent"] | components["schemas"]["ResponseInProgressStreamingEvent"] | components["schemas"]["ResponseCompletedStreamingEvent"] | components["schemas"]["ResponseFailedStreamingEvent"] | components["schemas"]["ResponseIncompleteStreamingEvent"] | components["schemas"]["ResponseOutputItemAddedStreamingEvent"] | components["schemas"]["ResponseOutputItemDoneStreamingEvent"] | components["schemas"]["ResponseReasoningSummaryPartAddedStreamingEvent"] | components["schemas"]["ResponseReasoningSummaryPartDoneStreamingEvent"] | components["schemas"]["ResponseContentPartAddedStreamingEvent"] | components["schemas"]["ResponseContentPartDoneStreamingEvent"] | components["schemas"]["ResponseOutputTextDeltaStreamingEvent"] | components["schemas"]["ResponseOutputTextDoneStreamingEvent"] | components["schemas"]["ResponseRefusalDeltaStreamingEvent"] | components["schemas"]["ResponseRefusalDoneStreamingEvent"] | components["schemas"]["ResponseReasoningDeltaStreamingEvent"] | components["schemas"]["ResponseReasoningDoneStreamingEvent"] | components["schemas"]["ResponseReasoningSummaryDeltaStreamingEvent"] | components["schemas"]["ResponseReasoningSummaryDoneStreamingEvent"] | components["schemas"]["ResponseOutputTextAnnotationAddedStreamingEvent"] | components["schemas"]["ResponseFunctionCallArgumentsDeltaStreamingEvent"] | components["schemas"]["ResponseFunctionCallArgumentsDoneStreamingEvent"] | components["schemas"]["ErrorStreamingEvent"];
                };
            };
        };
    };
}
